module.exports = {
  Help:   require("./help"),
  Ping:   require("./ping"),
  Soup:   require("./soupTime"),
  Say:    require('./say'),
  Pizza:  require('./pizzatime'),
  Issue:  require('./issue'),
  Server: require('./serverInfo'),
  Info:   require('./info'),
  Play:   require('./music').play,
  Stop:   require('./music').stop,
  Toggle:  require('./music').toggle,
  Skip:   require('./music').skip,
  // Add:    require('./music').add,
  Meme:   require('./meme'),
  // Music:  require('./music'),
  // Dice:   require("./diceRoll"),
};
